replicaCount: 1

image:
  pullPolicy: IfNotPresent
  name: entropydata/entropy-data-ce # use entropydata/entropy-data for enterprise version
  tag: 1.7.4 # check latest version

service:
  type: ClusterIP  # Can be ClusterIP, LoadBalancer, or NodePort
  port: 8080

entropydata:
  host: https://entropy-data.example.com

database:
  url: jdbc:postgresql://localhost:5432/postgres # change to your database URL
  secretName: entropy-data-database # create secret beforehand
  usernameKey: username
  passwordKey: password

smtp:
  host: smtp.example.com
  port: "1025"
  secretName: entropy-data-smtp # create secret beforehand
  usernameKey: username
  passwordKey: password

sso:
  azure:
    enabled: false
    issuerUri: "https://login.microsoftonline.com/YOUR_TENANT_UUID/v2.0"
    secretName: entropy-data-azure-sso # create secret beforehand
    clientIdKey: client-id
    clientSecretKey: client-secret

# Additional environment variables to be set in the deployment
# Format:
# env:
#   - name: VARIABLE_NAME
#     value: "variable-value"
env: []

resources:
  limits:
    cpu: 1
    memory: 2Gi
  requests:
    cpu: 1
    memory: 2Gi

startupProbe:
  httpGet:
    path: /login
    port: 8080
  failureThreshold: 30
  periodSeconds: 10
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 30
  httpGet:
    path: /login
    port: 8080
readinessProbe:
  httpGet:
    path: /login
    port: 8080

nodeSelector: {}

tolerations: []

affinity: {}