apiVersion: v1
kind: Service
metadata:
  name: entropy-data
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: entropy-data
