apiVersion: apps/v1
kind: Deployment
metadata:
  name: entropy-data
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: entropy-data
  template:
    metadata:
      name: entropy-data
      labels:
        app: entropy-data
    spec:
      containers:
        - name: entropy-data
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: DATAMESHMANAGER_HOST
              value: {{ .Values.entropydata.host }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.database.url }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.usernameKey }}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: {{ .Values.database.passwordKey }}
            - name: SPRING_MAIL_HOST
              value: {{ .Values.smtp.host }}
            - name: SPRING_MAIL_PORT
              value: {{ .Values.smtp.port | quote }}
            {{- if .Values.smtp.secretName }}
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: {{ .Values.smtp.usernameKey }}
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: {{ .Values.smtp.passwordKey }}
            {{- end }}      
            {{- if .Values.sso.azure.enabled }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AZURE_ISSUER_URI
              value: {{ .Values.sso.azure.issuerUri }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.azure.secretName }}
                  key: {{ .Values.sso.azure.clientIdKey }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.sso.azure.secretName }}
                  key: {{ .Values.sso.azure.clientSecretKey }}
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_PROVIDER
              value: azure
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_AUTHORIZATION_GRANT_TYPE
              value: authorization_code
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_REDIRECT_URI
              value: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_CLIENT_AUTHENTICATION_METHOD
              value: client_secret_basic
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AZURESSO_SCOPE
              value: openid,profile,email
            - name: APPLICATION_SSO_AZURE_HOSTS
              value: {{ .Values.entropydata.host | trimPrefix "https://" | trimPrefix "http://" }}
            {{- end }}
            {{- if .Values.env }}
            {{- toYaml .Values.env | nindent 12 }}
            {{- end }}
          {{- if .Values.startupProbe }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
